Update html_title.module
PHP message: ArgumentCountError: Too few arguments to function html_title_node_view(), 4 passed and exactly 5 expected in /html-ibbweld/modules/html_title/html_title.module on line 87 #0 [internal function]: html_title_node_view(Array, Object(Drupal\node\Entity\Node), Object(Drupal\Core\Entity\Entity\EntityViewDisplay), 'full')"

Solution was the remove $langcode since it is not requested.

https://api.drupal.org/api/drupal/core%21lib%21Drupal%21Core%21Entity%21entity.api.php/function/hook_ENTITY_TYPE_view/8.2.x